// Docentes iniciales
export const INIT_DOCENTES = [
  { id: 'd1', nombre: 'Ing. Carlos Mendoza', tipo: 'Civil', maxHoras: 25, especialidad: 'Matemáticas' },
  { id: 'd2', nombre: 'Cap. Roberto Díaz', tipo: 'Militar Activo', maxHoras: 25, especialidad: 'Doctrina' },
  { id: 'd3', nombre: 'Ing. Ana Pardo', tipo: 'Civil', maxHoras: 25, especialidad: 'Física' },
  { id: 'd4', nombre: 'Tcnl. Luis Vargas', tipo: 'Militar Reserva', maxHoras: 25, especialidad: 'Táctica' },
  { id: 'd5', nombre: 'Ing. Sofia Castro', tipo: 'Civil', maxHoras: 25, especialidad: 'Redes' },
  { id: 'd6', nombre: 'Ing. Fernando Rios', tipo: 'Civil', maxHoras: 25, especialidad: 'Sistemas' },
  { id: 'd7', nombre: 'My. Jorge Salinas', tipo: 'Militar Activo', maxHoras: 25, especialidad: 'Defensa' },
  { id: 'd8', nombre: 'Ing. Elena Gómez', tipo: 'Civil', maxHoras: 25, especialidad: 'Idiomas' },
  { id: 'd9', nombre: 'Ing. Raul Mamani', tipo: 'Civil', maxHoras: 25, especialidad: 'Bases de Datos' },
  { id: 'd10', nombre: 'Ing. Patricia Luna', tipo: 'Civil', maxHoras: 25, especialidad: 'Gestión' },
  { id: 'd11', nombre: 'Cap. Diego Blanco', tipo: 'Militar Activo', maxHoras: 25, especialidad: 'Doctrina' },
  { id: 'd12', nombre: 'Ing. Carmen Vega', tipo: 'Civil', maxHoras: 25, especialidad: 'Software' },
];

// Aulas iniciales
export const INIT_AULAS = [
  { id: 'a1', nombre: 'Aula 101', tipo: 'Aula', capacidad: 40, edificio: 'A', disponible: true },
  { id: 'a2', nombre: 'Aula 102', tipo: 'Aula', capacidad: 40, edificio: 'A', disponible: true },
  { id: 'a3', nombre: 'Aula 201', tipo: 'Aula', capacidad: 35, edificio: 'A', disponible: true },
  { id: 'a4', nombre: 'Lab. Computación 1', tipo: 'Laboratorio', capacidad: 30, edificio: 'B', disponible: true },
  { id: 'a5', nombre: 'Lab. Computación 2', tipo: 'Laboratorio', capacidad: 30, edificio: 'B', disponible: true },
  { id: 'a6', nombre: 'Lab. Redes', tipo: 'Laboratorio', capacidad: 25, edificio: 'B', disponible: true },
  { id: 'a7', nombre: 'Aula Magna', tipo: 'Auditorio', capacidad: 120, edificio: 'C', disponible: true },
  { id: 'a8', nombre: 'Sala de Conferencias', tipo: 'Sala', capacidad: 20, edificio: 'C', disponible: false },
];

// Materias iniciales
export const INIT_MATERIAS = [
  { id: 'm3_1', nombre: 'Cálculo III', semestre: 3, periodos: 3, docenteId: 'd1', tipoAula: 'Aula' },
  { id: 'm3_2', nombre: 'Física II', semestre: 3, periodos: 3, docenteId: 'd3', tipoAula: 'Aula' },
  { id: 'm3_3', nombre: 'Estructura de Datos', semestre: 3, periodos: 3, docenteId: 'd5', tipoAula: 'Laboratorio' },
  { id: 'm3_4', nombre: 'Estadística I', semestre: 3, periodos: 3, docenteId: 'd6', tipoAula: 'Aula' },
  { id: 'm3_5', nombre: 'Álgebra Lineal', semestre: 3, periodos: 2, docenteId: 'd1', tipoAula: 'Aula' },
  { id: 'm3_6', nombre: 'Doctrina Militar III', semestre: 3, periodos: 2, docenteId: 'd2', tipoAula: 'Aula' },
  { id: 'm3_7', nombre: 'Inglés III', semestre: 3, periodos: 2, docenteId: 'd8', tipoAula: 'Aula' },
  { id: 'm3_8', nombre: 'Contabilidad', semestre: 3, periodos: 2, docenteId: 'd10', tipoAula: 'Aula' },
  { id: 'm4_1', nombre: 'Ecuaciones Diferenciales', semestre: 4, periodos: 3, docenteId: 'd1', tipoAula: 'Aula' },
  { id: 'm4_2', nombre: 'Bases de Datos I', semestre: 4, periodos: 3, docenteId: 'd6', tipoAula: 'Laboratorio' },
  { id: 'm4_3', nombre: 'Prog. Orientada a Objetos', semestre: 4, periodos: 3, docenteId: 'd5', tipoAula: 'Laboratorio' },
  { id: 'm4_4', nombre: 'Estadística II', semestre: 4, periodos: 3, docenteId: 'd9', tipoAula: 'Aula' },
  { id: 'm4_5', nombre: 'Física III', semestre: 4, periodos: 3, docenteId: 'd3', tipoAula: 'Aula' },
  { id: 'm4_6', nombre: 'Doctrina Militar IV', semestre: 4, periodos: 3, docenteId: 'd7', tipoAula: 'Aula' },
  { id: 'm4_7', nombre: 'Inglés IV', semestre: 4, periodos: 2, docenteId: 'd8', tipoAula: 'Aula' },
  { id: 'm5_1', nombre: 'Bases de Datos II', semestre: 5, periodos: 3, docenteId: 'd6', tipoAula: 'Laboratorio' },
  { id: 'm5_2', nombre: 'Sistemas Operativos', semestre: 5, periodos: 3, docenteId: 'd9', tipoAula: 'Laboratorio' },
  { id: 'm5_3', nombre: 'Análisis y Diseño', semestre: 5, periodos: 3, docenteId: 'd12', tipoAula: 'Aula' },
  { id: 'm5_4', nombre: 'Investigación Operativa I', semestre: 5, periodos: 3, docenteId: 'd1', tipoAula: 'Aula' },
  { id: 'm5_5', nombre: 'Redes I', semestre: 5, periodos: 2, docenteId: 'd5', tipoAula: 'Laboratorio' },
  { id: 'm5_6', nombre: 'Doctrina Militar V', semestre: 5, periodos: 2, docenteId: 'd11', tipoAula: 'Aula' },
  { id: 'm5_7', nombre: 'Inglés V', semestre: 5, periodos: 2, docenteId: 'd8', tipoAula: 'Aula' },
  { id: 'm5_8', nombre: 'Economía General', semestre: 5, periodos: 2, docenteId: 'd10', tipoAula: 'Aula' },
  { id: 'm6_1', nombre: 'Ingeniería de Software I', semestre: 6, periodos: 3, docenteId: 'd12', tipoAula: 'Laboratorio' },
  { id: 'm6_2', nombre: 'Redes II', semestre: 6, periodos: 3, docenteId: 'd5', tipoAula: 'Laboratorio' },
  { id: 'm6_3', nombre: 'Investigación Operativa II', semestre: 6, periodos: 3, docenteId: 'd1', tipoAula: 'Aula' },
  { id: 'm6_4', nombre: 'Sistemas de Inf. Geográfica', semestre: 6, periodos: 3, docenteId: 'd9', tipoAula: 'Laboratorio' },
  { id: 'm6_5', nombre: 'Arquitectura de Computadoras', semestre: 6, periodos: 3, docenteId: 'd6', tipoAula: 'Aula' },
  { id: 'm6_6', nombre: 'Táctica y Estrategia I', semestre: 6, periodos: 3, docenteId: 'd4', tipoAula: 'Aula' },
  { id: 'm6_7', nombre: 'Preparación de Proyectos', semestre: 6, periodos: 2, docenteId: 'd10', tipoAula: 'Aula' },
  { id: 'm7_1', nombre: 'Ingeniería de Software II', semestre: 7, periodos: 3, docenteId: 'd12', tipoAula: 'Laboratorio' },
  { id: 'm7_2', nombre: 'Sistemas Distribuidos', semestre: 7, periodos: 3, docenteId: 'd9', tipoAula: 'Laboratorio' },
  { id: 'm7_3', nombre: 'Inteligencia Artificial', semestre: 7, periodos: 3, docenteId: 'd6', tipoAula: 'Laboratorio' },
  { id: 'm7_4', nombre: 'Seguridad de Sistemas', semestre: 7, periodos: 3, docenteId: 'd5', tipoAula: 'Laboratorio' },
  { id: 'm7_5', nombre: 'Dinámica de Sistemas', semestre: 7, periodos: 3, docenteId: 'd3', tipoAula: 'Aula' },
  { id: 'm7_6', nombre: 'Táctica y Estrategia II', semestre: 7, periodos: 3, docenteId: 'd4', tipoAula: 'Aula' },
  { id: 'm7_7', nombre: 'Evaluación de Proyectos', semestre: 7, periodos: 2, docenteId: 'd10', tipoAula: 'Aula' },
  { id: 'm8_1', nombre: 'Auditoría de Sistemas', semestre: 8, periodos: 3, docenteId: 'd12', tipoAula: 'Laboratorio' },
  { id: 'm8_2', nombre: 'Sistemas Expertos', semestre: 8, periodos: 3, docenteId: 'd6', tipoAula: 'Laboratorio' },
  { id: 'm8_3', nombre: 'Redes Inalámbricas', semestre: 8, periodos: 3, docenteId: 'd5', tipoAula: 'Laboratorio' },
  { id: 'm8_4', nombre: 'Legislación para Ingeniería', semestre: 8, periodos: 3, docenteId: 'd10', tipoAula: 'Aula' },
  { id: 'm8_5', nombre: 'Metodología de la Investigación', semestre: 8, periodos: 3, docenteId: 'd8', tipoAula: 'Aula' },
  { id: 'm8_6', nombre: 'Liderazgo Militar', semestre: 8, periodos: 3, docenteId: 'd2', tipoAula: 'Aula' },
  { id: 'm8_7', nombre: 'Simulación de Sistemas', semestre: 8, periodos: 2, docenteId: 'd3', tipoAula: 'Laboratorio' },
  { id: 'm9_1', nombre: 'Taller de Grado I', semestre: 9, periodos: 4, docenteId: 'd12', tipoAula: 'Laboratorio' },
  { id: 'm9_2', nombre: 'Planificación Estratégica', semestre: 9, periodos: 4, docenteId: 'd10', tipoAula: 'Aula' },
  { id: 'm9_3', nombre: 'Gestión de Calidad de Software', semestre: 9, periodos: 4, docenteId: 'd6', tipoAula: 'Laboratorio' },
  { id: 'm9_4', nombre: 'Comercio Electrónico', semestre: 9, periodos: 4, docenteId: 'd9', tipoAula: 'Laboratorio' },
  { id: 'm9_5', nombre: 'Defensa Nacional', semestre: 9, periodos: 4, docenteId: 'd7', tipoAula: 'Aula' },
  { id: 'm10_1', nombre: 'Taller de Grado II', semestre: 10, periodos: 4, docenteId: 'd12', tipoAula: 'Laboratorio' },
  { id: 'm10_2', nombre: 'Gerencia de Sistemas', semestre: 10, periodos: 4, docenteId: 'd10', tipoAula: 'Aula' },
  { id: 'm10_3', nombre: 'Robótica', semestre: 10, periodos: 4, docenteId: 'd5', tipoAula: 'Laboratorio' },
  { id: 'm10_4', nombre: 'Minería de Datos', semestre: 10, periodos: 4, docenteId: 'd6', tipoAula: 'Laboratorio' },
  { id: 'm10_5', nombre: 'Geopolítica', semestre: 10, periodos: 4, docenteId: 'd4', tipoAula: 'Aula' },
];
